services:
  coturn:
    image: coturn/coturn:latest
    container_name: eblusha-coturn
    restart: unless-stopped
    network_mode: host
    command: ["-c", "/etc/coturn/turnserver.conf"]
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./certs:/etc/coturn/certs:ro
      - ./data:/var/lib/coturn
